name: GHA 1
on: 
    workflow_dispatch: 
jobs:
  testing:
      name: testing files
      runs-on: ubuntu-latest
      steps:
          - name: reading repo files using actions
            uses: actions/checkout@v4
          - name: listing files
            run: |
                   echo "welcome to GHA"
                   ls -la
                   cat index.html
  
            # - name: ASCII Artwork
            #   run: cowsay  -f  dragon   "Run for cover,   Dragon is there"
